-- MySQL
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    BS.CATEGORY,
    SUM(BS.BOOK_TOTAL_SALES) AS TOTAL_SALES
FROM
    (SELECT
        B.BOOK_ID,
        B.AUTHOR_ID,
        B.CATEGORY,
        S.SALES_DATE,
        SUM(S.SALES * B.PRICE) AS BOOK_TOTAL_SALES
    FROM 
        BOOK B, 
        BOOK_SALES S
    WHERE 
        B.BOOK_ID = S.BOOK_ID
    GROUP BY
        B.BOOK_ID,
        B.AUTHOR_ID,
        B.CATEGORY,
        S.SALES_DATE) BS
JOIN
    AUTHOR A
    ON BS.AUTHOR_ID = A.AUTHOR_ID
WHERE
    BS.SALES_DATE LIKE '2022-01%'
GROUP BY
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    BS.CATEGORY
ORDER BY
    1 ASC,
    3 DESC
;