SELECT 
    I.FOOD_TYPE,
    I.REST_ID,
    I.REST_NAME,
    I.FAVORITES
FROM 
    REST_INFO I
JOIN
    (SELECT 
        FOOD_TYPE, 
        MAX(FAVORITES) AS MAX_FAVOR
    FROM 
        REST_INFO
    GROUP BY 
        FOOD_TYPE) 
    AS F
    ON I.FOOD_TYPE = F.FOOD_TYPE
    AND I.FAVORITES = F.MAX_FAVOR
ORDER BY 
    I.FOOD_TYPE DESC;