-- 코드를 입력하세요
SELECT
    P.*
FROM
    PLACES P
JOIN
    (SELECT ID, HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) > 1)
    AS P_CNT
    ON P.HOST_ID = P_CNT.HOST_ID
WHERE
    P.HOST_ID = P_CNT.HOST_ID
ORDER BY
    ID;