-- MySQL
WITH RECURSIVE HOURS AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

SELECT
    LPAD(HOURS.HOUR, 2, '0') AS HOUR,
    IFNULL(COUNT(O.DATETIME), 0) AS COUNT
FROM 
    HOURS
LEFT JOIN 
    ANIMAL_OUTS O 
    ON HOUR(O.DATETIME) = HOURS.HOUR
GROUP BY
    HOURS.HOUR
ORDER BY
    HOUR ASC
;