-- MySQL
SELECT
    I.ID,
    N.FISH_NAME,
    I.LENGTH
FROM
    FISH_INFO I
JOIN
    FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
JOIN
    (SELECT 
        FISH_TYPE,
        MAX(LENGTH) AS MAXLEN
     FROM 
        FISH_INFO
     GROUP BY 
        FISH_TYPE) M
    ON I.FISH_TYPE = M.FISH_TYPE
    AND I.LENGTH = M.MAXLEN
ORDER BY
    I.ID ASC
;